Handle sigterm and Ctrl-C (sigint)

diff --git a/usr/Loop b/usr/Loop
--- a/usr/Loop
+++ b/usr/Loop
@@ -1,10 +1,17 @@
 #!/bin/bash
+
+# $* orTest
 if [ -n "$1" ] ; then
   export PROG="$*"
 else
   export PROG="./Test"
 fi
 
+# Interrupt
+export ABORT=0
+trap "ABORT=1" SIGINT SIGTERM
+
+# Loop until failure or interrupt
 res=0
 let n=0+1
 while [ $res -eq 0 ] ; do
@@ -13,6 +20,9 @@ while [ $res -eq 0 ] ; do
   if [ $? -ne 0 ] ; then
     echo "Failed!"
     exit 1
+  elif [ $ABORT -eq 1 ] ; then
+    echo "Aborted"
+    exit 0
   fi
   let n=$n+1
 done
