Add Short mode and improve tests

diff --git a/usr/misc/Test b/usr/misc/Test
--- a/usr/misc/Test
+++ b/usr/misc/Test
@@ -140,8 +140,7 @@ elif [ "$1"  = "--lz4l" ] ; then
   exit
 fi
 
-# Default
-if [ "$1" != "--none" ] ; then
+if [ \( -z "$1" \) -o \( "$1" = "compress" \) ] ; then
   # Azf on lzf, lz4 and snappy
   for file in `ls *.ads *.adb lib/*` ; do
     cmpr_one --lzf $file
@@ -152,11 +151,12 @@ if [ "$1" != "--none" ] ; then
   echo ""
 fi
 
-# Comp_vars with SET_ME set
-echo "comp_vars with SET_ME"
-export SET_ME=Momo
-comp_vars < variables.xml >out 2>err
-cat > expout << EOF
+if [ \( -z "$1" \) -o \( "$1" = "comp_vars" \) ] ; then
+  # Comp_vars with SET_ME set
+  echo "comp_vars with SET_ME"
+  export SET_ME=Momo
+  comp_vars < variables.xml >out 2>err
+  cat > expout << EOF
 <?xml version="1.1"?>
 <Variables>
   <Var Name="V1" Type="Int">5</Var>
@@ -168,67 +168,69 @@ cat > expout << EOF
   <Var Name="Fail" Type="Str">Momo</Var>
 </Variables>
 EOF
-echo -n > experr
-comp out expout
-comp err experr
+  echo -n > experr
+  comp out expout
+  comp err experr
 
-# Comp_vars without SET_ME set
-echo "comp_vars without SET_ME"
-unset SET_ME
-comp_vars < variables.xml >out 2>err
-cat > experr << EOF 
+  # Comp_vars without SET_ME set
+  echo "comp_vars without SET_ME"
+  unset SET_ME
+  comp_vars < variables.xml >out 2>err
+  cat > experr << EOF 
 Error: Environ variable SET_ME not found.
 Error processing input flow at line 15 on node Var:
 Unknown variable while evaluating variable.
 EOF
-comp err experr
-echo ""
+  comp err experr
+  echo ""
+fi
 
-# Intercept
-echo -n "" > experr
-let L=1
-while true ; do
-  QFU=`readarg interceptions.txt $L 1`
-  if [ "QFU" = "#" ] ; then
-    continue;
-  fi
-  if [ -z "$QFU" ] ; then
-    break;
-  fi
-  HEADING=`readarg interceptions.txt $L 2`
-  KIND=`readarg interceptions.txt $L 3`
-  case "$KIND" in
-    ("You")
-      KIND="Final"
-      echo  "You are in final heading $QFU." > expout
-    ;;
-    ("Direct")
-      TD1=`readarg interceptions.txt $L  4`
-      HD1=`readarg interceptions.txt $L  5`
-      TA1=`readarg interceptions.txt $L  6`
-      HA1=`readarg interceptions.txt $L  7`
-      MA2=`readarg interceptions.txt $L  8`
-      TA2=`readarg interceptions.txt $L  9`
-      HA2=`readarg interceptions.txt $L 10`
-cat > expout << EOF
+if [ \( -z "$1" \) -o \( "$1" = "intercept" \) ] ; then
+  # Intercept
+  echo -n "" > experr
+  let L=1
+  while true ; do
+    QFU=`readarg interceptions.txt $L 1`
+    if [ "QFU" = "#" ] ; then
+      continue;
+    fi
+    if [ -z "$QFU" ] ; then
+      break;
+    fi
+    HEADING=`readarg interceptions.txt $L 2`
+    KIND=`readarg interceptions.txt $L 3`
+    case "$KIND" in
+      ("Final")
+        KIND="Final"
+        echo  "You are in final heading $QFU." > expout
+      ;;
+      ("Direct")
+        TD1=`readarg interceptions.txt $L  4`
+        HD1=`readarg interceptions.txt $L  5`
+        TA1=`readarg interceptions.txt $L  6`
+        HA1=`readarg interceptions.txt $L  7`
+        MA2=`readarg interceptions.txt $L  8`
+        TA2=`readarg interceptions.txt $L  9`
+        HA2=`readarg interceptions.txt $L 10`
+  cat > expout << EOF
 Direct interception
 At DME 30 turn $TD1 heading $HD1 to intercept final heading $QFU.
 Alternate indirect interception
 At DME 30 turn $TA1 heading $HA1,
 at DME 22 QDM $MA2 turn $TA2 heading $HA2 to intercept final heading $QFU.
 EOF
-    ;;  
-    ("Indirect")
-      TI1=`readarg interceptions.txt $L  4`
-      HI1=`readarg interceptions.txt $L  5`
-      MI2=`readarg interceptions.txt $L  6`
-      TI2=`readarg interceptions.txt $L  7`
-      HI2=`readarg interceptions.txt $L  8`
-      TA1=`readarg interceptions.txt $L  9`
-      HA1=`readarg interceptions.txt $L 10`
-      MA2=`readarg interceptions.txt $L 11`
-      TA2=`readarg interceptions.txt $L 12`
-      HA2=`readarg interceptions.txt $L 13`
+      ;;  
+      ("Indirect")
+        TI1=`readarg interceptions.txt $L  4`
+        HI1=`readarg interceptions.txt $L  5`
+        MI2=`readarg interceptions.txt $L  6`
+        TI2=`readarg interceptions.txt $L  7`
+        HI2=`readarg interceptions.txt $L  8`
+        TA1=`readarg interceptions.txt $L  9`
+        HA1=`readarg interceptions.txt $L 10`
+        MA2=`readarg interceptions.txt $L 11`
+        TA2=`readarg interceptions.txt $L 12`
+        HA2=`readarg interceptions.txt $L 13`
       cat > expout << EOF
 Indirect interception
 At DME 30 turn $TI1 heading $HI1,
@@ -237,21 +239,22 @@ Alternate indirect interception
 At DME 30 turn $TA1 heading $HA1,
 at DME 22 QDM $MA2 turn $TA2 heading $HA2 to intercept final heading $QFU.
 EOF
-    ;;
-    (*)
-      echo "Invalid kind $LIND" 1>&2
-      exit 1
-    ;;
-  esac
-  echo "intercept $QFU $HEADING $KIND"
-  intercept $QFU $HEADING >out 2>err
-  comp out expout
-  comp err experr
-  let L=$L+1
-done
+      ;;
+      (*)
+        echo "Invalid kind $LIND" 1>&2
+        exit 1
+      ;;
+    esac
+    echo "intercept $QFU $HEADING $KIND"
+    intercept $QFU $HEADING >out 2>err
+    comp out expout
+    comp err experr
+    let L=$L+1
+  done
 
+  # Done
+  echo ""
+fi
 
-# Done
-echo "OK"
 clean
 
