Check result of azf

diff --git a/usr/misc/Test b/usr/misc/Test
--- a/usr/misc/Test
+++ b/usr/misc/Test
@@ -12,7 +12,17 @@ trap 'echo ""; clean; exit 1' SIGINT SIGTERM
 for file in `ls *.ads *.adb` ; do
   echo azf $file
   cat $file | azf -c > cmp
+  if [ $? -ne 0 ] ; then
+    echo "Azf -c has failed." 2>&1
+    exit 1
+  fi
+
   cat cmp | azf -d > res
+  if [ $? -ne 0 ] ; then
+    echo "Azf -d has failed." 2>&1
+    exit 1
+  fi
+
   cmp $file res 2>/dev/null
   res=$?
   if [ $res -ne 0 ] ; then
