Add sort by name+activity Keep current position in activity list

diff --git a/usr/heart/data/heart b/usr/heart/data/heart
--- a/usr/heart/data/heart
+++ b/usr/heart/data/heart
@@ -25,6 +25,16 @@ while [ -n "$1" ] ; do
     # Option for not launch
     LAUNCH=0
     shift
+  elif [ \( "$1" = "-h" \) -o \( "$1" = "--help" \) ] ; then
+    echo "Usage: `basename $0` [ <import_tmp> ] [ <no_sync> ] [ <dry_run> ] [ <no_heart> ]"
+    echo "  <import_tmp> ::= -t | --tmp       // Import from '$HOME'/tmp"
+    echo "  <no_sync>    ::= -S | --no-sync   // No synchro of data files"
+    echo "  <dry_run>    ::= -d | --dry-run   // Dry run of synchro"
+    echo "  <no_heart>   ::= -H | --no-heart  // Only synchro (no launch of heart)"
+    exit
+  else
+    echo "ERROR: Unsupported option $1." 1>&2
+    exit 1
   fi
 done
 
