Check integer arguments

diff --git a/usr/geo_codes/mapcode/fullaccuracy b/usr/geo_codes/mapcode/fullaccuracy
--- a/usr/geo_codes/mapcode/fullaccuracy
+++ b/usr/geo_codes/mapcode/fullaccuracy
@@ -8,11 +8,17 @@ function usage {
   echo "    or `basename $0` [ -h | --help ]"
 }
 
+function error {
+  echo "ERROR: $1."
+  usage
+  exit 1
+}
 
+# Parse options
 export WARN=""
 export THREADS=1
 export TDIR=test
-export PRECISION="P2"
+export PRECISION="2"
 
 T0=`date "+%s"`
 
@@ -26,11 +32,11 @@ while [ -n "$1" ] ; do
       WARN="-w"
     ;;
    ("-p")
-      export PRECISION="P$2"
+      export PRECISION="$2"
       shift
     ;;
     (--precision=*)
-      export PRECISION="P${1#*=}"
+      export PRECISION="${1#*=}"
     ;;
    ("-t")
       export THREADS=$2
@@ -40,12 +46,29 @@ while [ -n "$1" ] ; do
       export THREADS=${1#*=}
     ;;
     (*)
-      usage
-       exit 1
+      error "Invalid argument"
+      exit 1
     ;;
   esac
   shift
 done
+
+# Check values
+if ! [[ $PRECISION =~ [0-8] ]] ; then
+  error "Invalid precision"
+fi
+if ! [[ $THREADS =~ [1-4] ]] ; then
+  error "Invalid threads"
+fi
+
+# Put values
+echo -n "$THREADS thread"
+if [ $THREADS -ne 1 ] ; then
+  echo -n "s"
+fi
+echo ", precision $PRECISION"
+
+export PRECISION="P${PRECISION}"
 
 echo Encode
 while read -r lat lon || [[ -n "$lat" ]]; do
diff --git a/usr/geo_codes/mapcode/fulltest b/usr/geo_codes/mapcode/fulltest
--- a/usr/geo_codes/mapcode/fulltest
+++ b/usr/geo_codes/mapcode/fulltest
@@ -80,10 +80,11 @@ done
 if [ \( $SCENARIO_ONLY -eq 1 \) -a \( $TEST -eq 1 \) ] ; then
   error "Options \"scenario_only\" and \"test\" are mutually exclusive"
 fi
-let P=0+$PRECISION
-if [ \( $P -lt 0 \) -a \( $P -gt 8 \) ] ; then
-  error "Invalid precision $PRECISION"
+if ! [[ $PRECISION =~ [0-8] ]] ; then
+  error "Invalid precision"
 fi
+
+let P=0+$PRECISION
 echo Precision $PRECISION
 PRECISION=P${PRECISION}
 
