Fix redirection

diff --git a/usr/tcpchat/Test b/usr/tcpchat/Test
--- a/usr/tcpchat/Test
+++ b/usr/tcpchat/Test
@@ -69,7 +69,7 @@ function check {
   # Compare with expected
   cmp -s $1 $2
   if [ $? -ne 0 ] ; then
-    echo "ERROR: Result $1 differs from expected $2" 2>&1
+    echo "ERROR: Result $1 differs from expected $2" 1>&2
     exit 1
   else
     rm -f $1 $2
