Fix test

diff --git a/usr/astub/Test b/usr/astub/Test
--- a/usr/astub/Test
+++ b/usr/astub/Test
@@ -1,6 +1,6 @@
 #!/bin/bash
 function clean {
-  rm -f test.ads test.adb 
+  rm -f test.ads test.adb test.o test.ali
 }
 trap 'echo ""; clean; exit 1' SIGINT SIGTERM
 
@@ -15,16 +15,21 @@ if [ $? -ne 0 ] ; then
 fi
 cmp -s test.adb test.adb.ref
 res=$?
-if [ $res -eq 0 ] ; then
-  clean
-  echo Ok.
-  exit 0
-elif [ $res -eq 1 ] ; then
+if [ $res -eq 1 ] ; then
   echo "Error: Files differ."
   tkdiff test.adb.ref test.adb
-  exit 0
-else
+  exit 1
+elif [ $res -ne 0 ] ; then
   echo "An error occured while comparing."
   exit 1
 fi
+
+gnatmake test.adb >/dev/null 2>&1
+if [ $? -ne 0 ] ; then
+  echo "Error: test.adb does not compile"
+  exit 1
+fi
+clean
+echo Ok.
+exit 0
 
