Fix and test exit codes.

diff --git a/usr/asubst/Testasubt b/usr/asubst/Testasubt
--- a/usr/asubst/Testasubt
+++ b/usr/asubst/Testasubt
@@ -144,6 +144,67 @@ if [ "$res" != "\ntoto\ntiti\ntata" ] ; then
 fi
 echo "File substitution in test mode, OK."
 
+# Grep mode
+rm -rf $FS
+cp $FR $FT
+# Check multiple regexp grep
+res=`asubst -g " is\n" "" $FT`
+code=$?
+if [ $code -ne 0 ] ; then
+  echo "Error: asubst exited with code $code"
+  exit 1
+fi
+exp_res=`echo -e "tstfile.tst:Package body Pack is\n\ntstfile.tst:  procedure Test is\n\n"`
+if [ "$res" != "$exp_res" ] ; then
+  echo "Result $res differs from expected."
+  exit 1
+fi
+# Check mono regexp grep
+res=`asubst -g " is" "" $FT`
+if [ $code -ne 0 ] ; then
+  echo "Error: asubst exited with code $code"
+  exit 1
+fi
+exp_res=`echo -e "tstfile.tst:Package body Pack is\ntstfile.tst:  procedure Test is\n"`
+if [ "$res" != "$exp_res" ] ; then
+  echo "Result $res differs from expected toto."
+  exit 1
+fi
+cmp -s $FT $FR
+if [ $? -ne 0 ] ; then
+  echo "Result file $FT differs from expected $FR."
+  exit 1
+fi
+echo "Grep mode, OK."
+
+# Exit codes
+asubst -g > /dev/null 2>&1
+code=$?
+if [ $code != 2 ] ; then
+  echo "Error: asubst exited with code $code instead of 2"
+  exit 1
+fi
+asubst "[is" "is" $FT > /dev/null 2>&1
+code=$?
+if [ $code != 2 ] ; then
+  echo "Error: asubst exited with code $code instead of 2"
+  exit 1
+fi
+echo "That is the question" | asubst -g "[Tt]his" "" > /dev/null 2>&1
+code=$?
+if [ $code != 1 ] ; then
+  echo "Error: asubst exited with code $code instead of 1"
+  exit 1
+fi
+echo "That is the question" | asubst -g "[Tt]h.*is" "" > /dev/null 2>&1
+code=$?
+if [ $code != 0 ] ; then
+  echo "Error: asubst exited with code $code instead of 0"
+  exit 1
+fi
+echo "Exit codes, OK".
+
 # Cleanup test files
 rm -rf $FR $FT $FS $FE $FL
 echo "Test OK."
+
