On the way to 4.3. Fixing bugs.

diff --git a/usr/asubst/Testasubst b/usr/asubst/Testasubst
--- a/usr/asubst/Testasubst
+++ b/usr/asubst/Testasubst
@@ -215,6 +215,25 @@ if [ $? -ne 0 ] ; then
   echo "$STEP FAILED."
   exit 1
 fi
+# Check grep with exclusion
+res=`asubst -g "--exclude=Pack\sis" " is" "" $FT`
+if [ $code -ne 0 ] ; then
+  echo "Error: asubst exited with code $code"
+  echo "$STEP FAILED."
+  exit 1
+fi
+exp_res=`echo -e "tstfile.tst:  procedure Test is\n"`
+if [ "$res" != "$exp_res" ] ; then
+  echo "Result $res differs from expected toto."
+  echo "$STEP FAILED."
+  exit 1
+fi
+cmp -s $FT $FR
+if [ $? -ne 0 ] ; then
+  echo "Result file $FT differs from expected $FR."
+  echo "$STEP FAILED."
+  exit 1
+fi
 echo "$STEP OK."
 
 # Exit codes
diff --git a/usr/asubst/player b/usr/asubst/player
--- a/usr/asubst/player
+++ b/usr/asubst/player
@@ -29,6 +29,8 @@ res="`awk -vLINE=$1 -vFIELD=$2 -F '"' '
 echo "$res"
 }
 
+#Initially no option
+export opt=""
 # For each line
 let L=1
 while true ; do
@@ -37,24 +39,33 @@ while true ; do
   if [ "$input" = "" ] ; then
     break
   fi
-  export search=`readarg $L 2`
-  export replace=`readarg $L 3`
-  export expected=`readarg $L 4`
-  rexpected=`echo -e -n "$expected"`
-  # Do test and save exit status
-  echo "echo \"$input\" | asubst \"$search\" \"$replace\" -> $expected"
-  result=`echo -e -n "$input" | asubst "$search" "$replace"`
-  code=$?
-  export result
-  # Check exit status
-  if [ $code -ne 0 ] ; then
-    echo "Error: asubst exited with code $code"
-    exit 1
-  fi
-  # Check that result is expected
-  if [ "$result" != "$rexpected" ] ; then
-    echo "Error: expected $rexpected != got $result"
-    exit 1
+  if [ "$input" = "Option" ] ; then
+    export opt=`readarg $L 2`
+  else
+    export search=`readarg $L 2`
+    export replace=`readarg $L 3`
+    export expected=`readarg $L 4`
+    rexpected=`echo -e -n "$expected"`
+    # Do test and save exit status
+    if [ "$opt" != "" ] ; then
+    echo "echo \"$input\" | asubst \"$opt\" \"$search\" \"$replace\" -> $expected"
+      result=`echo -e -n "$input" | asubst "$opt" "$search" "$replace"`
+    else
+      echo "echo \"$input\" | asubst $opt \"$search\" \"$replace\" -> $expected"
+      result=`echo -e -n "$input" | asubst "$search" "$replace"`
+    fi
+    code=$?
+    export result
+    # Check exit status
+    if [ $code -eq 2 ] ; then
+      echo "Error: asubst exited with code $code"
+      exit 1
+    fi
+    # Check that result is expected
+    if [ "$result" != "$rexpected" ] ; then
+      echo "Error: expected $rexpected != got $result"
+      exit 1
+    fi
   fi
   let L=$L+1
 done
