Add automatic test of Tcp_Util

diff --git a/usr/tests/Test b/usr/tests/Test
--- a/usr/tests/Test
+++ b/usr/tests/Test
@@ -35,7 +35,7 @@ function launch {
   shift
   shift
 
-  echo "Sarting $command ($help):"
+  echo "Starting $command ($help):"
   if [ $null -eq 1 ] ; then
     $command $* >/dev/null
   else
@@ -128,6 +128,15 @@ function match {
   else
     return 1
   fi
+}
+
+# Export pid and exit code of process (in backgroup)
+child_pid=0
+function start_bg {
+  child_pid=$$
+  child_code=0
+  $*
+  child_code=$?
 }
 
 # Start list of function
@@ -2027,6 +2036,31 @@ X(  2) = 3.00000E+00
 EOF
   comp err nul
   comp out exp
+  echo "OK"
+fi
+
+# t_tcp_util
+if `match $arg t_tcp_util` ; then
+  title t_tcp_util...
+  # Start server then client and wait 10s
+  start_bg t_tcp_util -s -p50000 >outs 2>&1 &
+  ser_pid=$child_pid
+  sleep 0.3
+  start_bg t_tcp_util -clocalhost -p50000 -l40000 >outc 2>&1 &
+  cli_pid=$child_pid
+  sleep 10
+  # Stop client then server
+  kill $cli_pid
+  cli_code=$child_code
+  sleep 0.1
+  kill $ser_pid
+  ser_code=$child_code
+  if [ "$ser_cod" != 0 ] ; then
+    error "ERROR: server has exited with code $ser_code"
+  fi
+  if [ "$cli_cod" != 0 ] ; then
+    error "ERROR: client has exited with code $cli_code"
+  fi
   echo "OK"
 fi
 
