Add a test of Geo_Conv with known result

diff --git a/usr/great_circle/Test b/usr/great_circle/Test
--- a/usr/great_circle/Test
+++ b/usr/great_circle/Test
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# Acceptable delta whencomparing degrees
+export EPSILON="1E-6"
+
 # Error message
 function error {
   echo "ERROR: $1." 1>&2
@@ -33,6 +36,42 @@ function comp {
   else
     if [ $res -eq 0 ] ; then
       error "File $1 should differs from expected $2."
+    fi
+  fi
+}
+
+# Check that $2 = $3
+# if $1 is -d then compare floats modulo Epsilon (1.0E-6)
+# Echo 0 if OK and 1 otherwise
+function check {
+  if [ "$1" = "-d" ] ; then
+    echo $2 | awk -v EXPECT="$3" -v EPS="$EPSILON" '
+    function abs(v) {return v < 0 ? -v : v}
+    {
+      NEXPECT=split(EXPECT, EXPECTS)
+      NOUTPUT=split($0, OUTPUTS);
+      if (NEXPECT != NOUTPUT) {print "1"; exit}
+      for (i = 1; i < NEXPECT+1; i++) {
+        E = 0.0+EXPECTS[i]
+        O = 0.0+OUTPUTS[i]
+        D = abs(E - O)
+        if (D > EPS) {
+          if (E < 0.0) E += 360.0
+          if (O < 0.0) O += 360.0
+          D = abs(E - O)
+          if (D > EPS) {
+            print "1"
+          }
+        }
+      }
+      print "0"
+    }
+    '
+  else
+    if [ "$2" = "$3" ] ; then
+      echo 0
+    else
+      echo 1
     fi
   fi
 }
@@ -351,6 +390,45 @@ if [ $res -ne 0 ] ; then
   error "Random test failed"
 fi
 sleep 1
+
+# Launch geoconv $1 and check:
+# - 1st line versus EL1
+# - 2nd line versus EL2 (modulo Epsilon)
+# - if $2 != "", that $1 versus line $2
+export EL1="N50.03.5900/W005.42.5300"
+export EL2="50.066388900/-5.714722229"
+export PRECISIONS="4/8/7/14/14/11"
+function t_geo_conv {
+  echo "geo_conv $1 -p $PRECISIONS"
+  export RES=`geo_conv $1 -p $PRECISIONS`
+  if [ $? -ne 0 ] ; then
+    error "geo_conv has failed"
+  fi
+  L1=`echo -n $RES | cut -d ' ' -f 1`
+  chk=`check -t "$L1" "$EL1"`
+  if [ "$chk" != "0" ] ; then
+    error "$L1 /= $EL1"
+  fi
+  L2=`echo -n $RES | cut -d ' ' -f 2`
+  chk=`check -d "L2" "EL2"`
+  if [ "$chk" != "0" ] ; then
+    error "$L2 /= $EL2"
+  fi
+  if [ -n "$2" ] ; then
+    LN=`echo -n $RES | cut -d ' ' -f $2`
+    chk=`check -t "$1" $LN`
+    if [ "$chk" != "0" ] ; then
+      error "$1 /= $LN"
+    fi
+  fi
+}
+
+t_geo_conv N50.03.5900/W005.42.5300 1
+t_geo_conv 50.06638890/-5.71472223 2
+t_geo_conv VH05L.WLQG-6WVDY4Q 3
+t_geo_conv 9C2P378P+H42HPR 4
+t_geo_conv bdTVK5PNK4DlK7 5
+t_geo_conv gbguvfq9v76 6
 
 # Done
 #-----
